/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as PrimeiroContatoRouteImport } from './routes/primeiro-contato'
import { Route as PerfilIgRouteImport } from './routes/perfil-ig'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as FotoStoryRouteImport } from './routes/foto-story'
import { Route as FotoMensagemRouteImport } from './routes/foto-mensagem'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScanToolRouteImport } from './routes/scan.$tool'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const PrimeiroContatoRoute = PrimeiroContatoRouteImport.update({
  id: '/primeiro-contato',
  path: '/primeiro-contato',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilIgRoute = PerfilIgRouteImport.update({
  id: '/perfil-ig',
  path: '/perfil-ig',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const FotoStoryRoute = FotoStoryRouteImport.update({
  id: '/foto-story',
  path: '/foto-story',
  getParentRoute: () => rootRouteImport,
} as any)
const FotoMensagemRoute = FotoMensagemRouteImport.update({
  id: '/foto-mensagem',
  path: '/foto-mensagem',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanToolRoute = ScanToolRouteImport.update({
  id: '/scan/$tool',
  path: '/scan/$tool',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/foto-mensagem': typeof FotoMensagemRoute
  '/foto-story': typeof FotoStoryRoute
  '/historico': typeof HistoricoRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/perfil-ig': typeof PerfilIgRoute
  '/primeiro-contato': typeof PrimeiroContatoRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/scan/$tool': typeof ScanToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/foto-mensagem': typeof FotoMensagemRoute
  '/foto-story': typeof FotoStoryRoute
  '/historico': typeof HistoricoRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/perfil-ig': typeof PerfilIgRoute
  '/primeiro-contato': typeof PrimeiroContatoRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/scan/$tool': typeof ScanToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/foto-mensagem': typeof FotoMensagemRoute
  '/foto-story': typeof FotoStoryRoute
  '/historico': typeof HistoricoRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/perfil-ig': typeof PerfilIgRoute
  '/primeiro-contato': typeof PrimeiroContatoRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/scan/$tool': typeof ScanToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/foto-mensagem'
    | '/foto-story'
    | '/historico'
    | '/login'
    | '/perfil'
    | '/perfil-ig'
    | '/primeiro-contato'
    | '/recuperar-senha'
    | '/reset-password'
    | '/sitemap.xml'
    | '/scan/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/foto-mensagem'
    | '/foto-story'
    | '/historico'
    | '/login'
    | '/perfil'
    | '/perfil-ig'
    | '/primeiro-contato'
    | '/recuperar-senha'
    | '/reset-password'
    | '/sitemap.xml'
    | '/scan/$tool'
  id:
    | '__root__'
    | '/'
    | '/cadastro'
    | '/foto-mensagem'
    | '/foto-story'
    | '/historico'
    | '/login'
    | '/perfil'
    | '/perfil-ig'
    | '/primeiro-contato'
    | '/recuperar-senha'
    | '/reset-password'
    | '/sitemap.xml'
    | '/scan/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroRoute: typeof CadastroRoute
  FotoMensagemRoute: typeof FotoMensagemRoute
  FotoStoryRoute: typeof FotoStoryRoute
  HistoricoRoute: typeof HistoricoRoute
  LoginRoute: typeof LoginRoute
  PerfilRoute: typeof PerfilRoute
  PerfilIgRoute: typeof PerfilIgRoute
  PrimeiroContatoRoute: typeof PrimeiroContatoRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ScanToolRoute: typeof ScanToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/primeiro-contato': {
      id: '/primeiro-contato'
      path: '/primeiro-contato'
      fullPath: '/primeiro-contato'
      preLoaderRoute: typeof PrimeiroContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil-ig': {
      id: '/perfil-ig'
      path: '/perfil-ig'
      fullPath: '/perfil-ig'
      preLoaderRoute: typeof PerfilIgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foto-story': {
      id: '/foto-story'
      path: '/foto-story'
      fullPath: '/foto-story'
      preLoaderRoute: typeof FotoStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foto-mensagem': {
      id: '/foto-mensagem'
      path: '/foto-mensagem'
      fullPath: '/foto-mensagem'
      preLoaderRoute: typeof FotoMensagemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/$tool': {
      id: '/scan/$tool'
      path: '/scan/$tool'
      fullPath: '/scan/$tool'
      preLoaderRoute: typeof ScanToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroRoute: CadastroRoute,
  FotoMensagemRoute: FotoMensagemRoute,
  FotoStoryRoute: FotoStoryRoute,
  HistoricoRoute: HistoricoRoute,
  LoginRoute: LoginRoute,
  PerfilRoute: PerfilRoute,
  PerfilIgRoute: PerfilIgRoute,
  PrimeiroContatoRoute: PrimeiroContatoRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ScanToolRoute: ScanToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
