/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResponderStoryRouteImport } from './routes/responder-story'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as RaioXRouteImport } from './routes/raio-x'
import { Route as PrimeiroContatoRouteImport } from './routes/primeiro-contato'
import { Route as PerfilIgRouteImport } from './routes/perfil-ig'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as MemoriaRouteImport } from './routes/memoria'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeituraRouteImport } from './routes/leitura'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as FotoStoryRouteImport } from './routes/foto-story'
import { Route as FotoMensagemRouteImport } from './routes/foto-mensagem'
import { Route as FlowRouteImport } from './routes/flow'
import { Route as CantadasRouteImport } from './routes/cantadas'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScanToolRouteImport } from './routes/scan.$tool'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponderStoryRoute = ResponderStoryRouteImport.update({
  id: '/responder-story',
  path: '/responder-story',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RaioXRoute = RaioXRouteImport.update({
  id: '/raio-x',
  path: '/raio-x',
  getParentRoute: () => rootRouteImport,
} as any)
const PrimeiroContatoRoute = PrimeiroContatoRouteImport.update({
  id: '/primeiro-contato',
  path: '/primeiro-contato',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilIgRoute = PerfilIgRouteImport.update({
  id: '/perfil-ig',
  path: '/perfil-ig',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriaRoute = MemoriaRouteImport.update({
  id: '/memoria',
  path: '/memoria',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeituraRoute = LeituraRouteImport.update({
  id: '/leitura',
  path: '/leitura',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const FotoStoryRoute = FotoStoryRouteImport.update({
  id: '/foto-story',
  path: '/foto-story',
  getParentRoute: () => rootRouteImport,
} as any)
const FotoMensagemRoute = FotoMensagemRouteImport.update({
  id: '/foto-mensagem',
  path: '/foto-mensagem',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowRoute = FlowRouteImport.update({
  id: '/flow',
  path: '/flow',
  getParentRoute: () => rootRouteImport,
} as any)
const CantadasRoute = CantadasRouteImport.update({
  id: '/cantadas',
  path: '/cantadas',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanToolRoute = ScanToolRouteImport.update({
  id: '/scan/$tool',
  path: '/scan/$tool',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/cantadas': typeof CantadasRoute
  '/flow': typeof FlowRoute
  '/foto-mensagem': typeof FotoMensagemRoute
  '/foto-story': typeof FotoStoryRoute
  '/historico': typeof HistoricoRoute
  '/leitura': typeof LeituraRoute
  '/login': typeof LoginRoute
  '/memoria': typeof MemoriaRoute
  '/perfil': typeof PerfilRoute
  '/perfil-ig': typeof PerfilIgRoute
  '/primeiro-contato': typeof PrimeiroContatoRoute
  '/raio-x': typeof RaioXRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/responder-story': typeof ResponderStoryRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/scan/$tool': typeof ScanToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/cantadas': typeof CantadasRoute
  '/flow': typeof FlowRoute
  '/foto-mensagem': typeof FotoMensagemRoute
  '/foto-story': typeof FotoStoryRoute
  '/historico': typeof HistoricoRoute
  '/leitura': typeof LeituraRoute
  '/login': typeof LoginRoute
  '/memoria': typeof MemoriaRoute
  '/perfil': typeof PerfilRoute
  '/perfil-ig': typeof PerfilIgRoute
  '/primeiro-contato': typeof PrimeiroContatoRoute
  '/raio-x': typeof RaioXRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/responder-story': typeof ResponderStoryRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/scan/$tool': typeof ScanToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/cantadas': typeof CantadasRoute
  '/flow': typeof FlowRoute
  '/foto-mensagem': typeof FotoMensagemRoute
  '/foto-story': typeof FotoStoryRoute
  '/historico': typeof HistoricoRoute
  '/leitura': typeof LeituraRoute
  '/login': typeof LoginRoute
  '/memoria': typeof MemoriaRoute
  '/perfil': typeof PerfilRoute
  '/perfil-ig': typeof PerfilIgRoute
  '/primeiro-contato': typeof PrimeiroContatoRoute
  '/raio-x': typeof RaioXRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/responder-story': typeof ResponderStoryRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/scan/$tool': typeof ScanToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/cantadas'
    | '/flow'
    | '/foto-mensagem'
    | '/foto-story'
    | '/historico'
    | '/leitura'
    | '/login'
    | '/memoria'
    | '/perfil'
    | '/perfil-ig'
    | '/primeiro-contato'
    | '/raio-x'
    | '/recuperar-senha'
    | '/reset-password'
    | '/responder-story'
    | '/sitemap.xml'
    | '/scan/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/cantadas'
    | '/flow'
    | '/foto-mensagem'
    | '/foto-story'
    | '/historico'
    | '/leitura'
    | '/login'
    | '/memoria'
    | '/perfil'
    | '/perfil-ig'
    | '/primeiro-contato'
    | '/raio-x'
    | '/recuperar-senha'
    | '/reset-password'
    | '/responder-story'
    | '/sitemap.xml'
    | '/scan/$tool'
  id:
    | '__root__'
    | '/'
    | '/cadastro'
    | '/cantadas'
    | '/flow'
    | '/foto-mensagem'
    | '/foto-story'
    | '/historico'
    | '/leitura'
    | '/login'
    | '/memoria'
    | '/perfil'
    | '/perfil-ig'
    | '/primeiro-contato'
    | '/raio-x'
    | '/recuperar-senha'
    | '/reset-password'
    | '/responder-story'
    | '/sitemap.xml'
    | '/scan/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroRoute: typeof CadastroRoute
  CantadasRoute: typeof CantadasRoute
  FlowRoute: typeof FlowRoute
  FotoMensagemRoute: typeof FotoMensagemRoute
  FotoStoryRoute: typeof FotoStoryRoute
  HistoricoRoute: typeof HistoricoRoute
  LeituraRoute: typeof LeituraRoute
  LoginRoute: typeof LoginRoute
  MemoriaRoute: typeof MemoriaRoute
  PerfilRoute: typeof PerfilRoute
  PerfilIgRoute: typeof PerfilIgRoute
  PrimeiroContatoRoute: typeof PrimeiroContatoRoute
  RaioXRoute: typeof RaioXRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResponderStoryRoute: typeof ResponderStoryRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ScanToolRoute: typeof ScanToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/responder-story': {
      id: '/responder-story'
      path: '/responder-story'
      fullPath: '/responder-story'
      preLoaderRoute: typeof ResponderStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raio-x': {
      id: '/raio-x'
      path: '/raio-x'
      fullPath: '/raio-x'
      preLoaderRoute: typeof RaioXRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/primeiro-contato': {
      id: '/primeiro-contato'
      path: '/primeiro-contato'
      fullPath: '/primeiro-contato'
      preLoaderRoute: typeof PrimeiroContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil-ig': {
      id: '/perfil-ig'
      path: '/perfil-ig'
      fullPath: '/perfil-ig'
      preLoaderRoute: typeof PerfilIgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memoria': {
      id: '/memoria'
      path: '/memoria'
      fullPath: '/memoria'
      preLoaderRoute: typeof MemoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leitura': {
      id: '/leitura'
      path: '/leitura'
      fullPath: '/leitura'
      preLoaderRoute: typeof LeituraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foto-story': {
      id: '/foto-story'
      path: '/foto-story'
      fullPath: '/foto-story'
      preLoaderRoute: typeof FotoStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foto-mensagem': {
      id: '/foto-mensagem'
      path: '/foto-mensagem'
      fullPath: '/foto-mensagem'
      preLoaderRoute: typeof FotoMensagemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flow': {
      id: '/flow'
      path: '/flow'
      fullPath: '/flow'
      preLoaderRoute: typeof FlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cantadas': {
      id: '/cantadas'
      path: '/cantadas'
      fullPath: '/cantadas'
      preLoaderRoute: typeof CantadasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/$tool': {
      id: '/scan/$tool'
      path: '/scan/$tool'
      fullPath: '/scan/$tool'
      preLoaderRoute: typeof ScanToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroRoute: CadastroRoute,
  CantadasRoute: CantadasRoute,
  FlowRoute: FlowRoute,
  FotoMensagemRoute: FotoMensagemRoute,
  FotoStoryRoute: FotoStoryRoute,
  HistoricoRoute: HistoricoRoute,
  LeituraRoute: LeituraRoute,
  LoginRoute: LoginRoute,
  MemoriaRoute: MemoriaRoute,
  PerfilRoute: PerfilRoute,
  PerfilIgRoute: PerfilIgRoute,
  PrimeiroContatoRoute: PrimeiroContatoRoute,
  RaioXRoute: RaioXRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResponderStoryRoute: ResponderStoryRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ScanToolRoute: ScanToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
